name: Java CI

on:
  push:
    branches: [ main ]  # Solo cuando haces push a main
  pull_request:
    branches: [ main ]  # Opcional: también cuando haces PR a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Construir y correr tests con Maven
        run: mvn clean verify
